export const researchMethod = [
  { step: "01", label: "Question", note: "What am I trying to understand?" },
  { step: "02", label: "Hypothesis", note: "What do I currently think will happen?" },
  { step: "03", label: "Method", note: "How will I investigate it?" },
  { step: "04", label: "Data", note: "What information am I using?" },
  { step: "05", label: "Analysis", note: "What does the data show?" },
  { step: "06", label: "Results", note: "What did I discover?" },
  { step: "07", label: "Limitations", note: "What might make this unreliable?" },
  { step: "08", label: "Conclusion", note: "What did I learn?" },
  { step: "09", label: "Next Question", note: "What should I investigate next?" },
];

export type EntryStatus = "complete" | "in-progress" | "open";

export type ResearchEntry = {
  slug: string;
  index: string;
  question: string;
  field: string;
  status: EntryStatus;
  opened: string;
  summary: string;
  log?: {
    hypothesis: string[];
    method: string[];
    data: string[];
    analysis: string[];
    results: string[];
    limitations: string[];
    conclusion: string[];
    next: string[];
  };
};

export const entries: ResearchEntry[] = [
  {
    slug: "can-i-tell-a-random-walk-from-a-real-price-series",
    index: "R-01",
    question: "Can I tell a random walk from a real price series by eye?",
    field: "Probability",
    status: "complete",
    opened: "2026-03-02",
    summary:
      "If chart patterns carry information, I should be able to distinguish a real price history from a series generated by a random number generator. I tested whether I could.",
    log: {
      hypothesis: [
        "I expected to score well above chance — perhaps 70–80%. Real price series felt to me like they had a texture that random ones would not.",
      ],
      method: [
        "Generate 20 random walks with drift and volatility matched roughly to a real index. Take 20 real 250-day windows. Shuffle, strip axis labels, and classify each one as real or generated.",
        "Record the answer before revealing the label. Repeat over three sittings so that fatigue is not confounded with learning.",
      ],
      data: [
        "60 charts in total across three sittings. Real series taken from daily closing values; generated series from a normal distribution with matched mean and standard deviation of log returns.",
      ],
      analysis: [
        "I classified 33 of 60 correctly. Chance is 30. A binomial test on that result gives a p-value of roughly 0.44 — entirely consistent with guessing.",
        "My confidence, which I also recorded, was not correlated with being right. The charts I was most sure about were not the ones I got right.",
      ],
      results: [
        "I cannot distinguish them. More uncomfortably, I felt as though I could.",
      ],
      limitations: [
        "My generated series used constant volatility, which real markets do not have. A more realistic generator with volatility clustering might have been easier or harder to spot — I do not know which.",
        "Sample size of 60 is small. The confidence interval on 55% accuracy is wide enough to include a genuine small skill.",
        "I knew the design of the experiment, which may have biased how I looked at the charts.",
      ],
      conclusion: [
        "The visual patterns I was reading were not evidence. That does not prove markets are random — it proves that my eye is not an instrument capable of detecting the difference.",
        "The useful lesson is narrower than 'technical analysis does not work'. It is: my subjective sense of pattern is not admissible as data.",
      ],
      next: [
        "Does a simple statistical test — an autocorrelation of returns — do better than I did? And if it does, is the effect large enough to survive transaction costs?",
      ],
    },
  },
  {
    slug: "does-a-longer-horizon-reduce-the-risk-of-loss",
    index: "R-02",
    question: "Does a longer holding period actually reduce the risk of loss?",
    field: "Finance / Statistics",
    status: "in-progress",
    opened: "2026-05-11",
    summary:
      "The claim that 'stocks are safe if you hold them long enough' is repeated constantly. I want to check what it means precisely, and whether it survives being made precise.",
  },
  {
    slug: "how-much-does-a-1-percent-fee-cost-over-a-lifetime",
    index: "R-03",
    question: "How much does a 1% annual fee cost over a lifetime?",
    field: "Mathematics / Finance",
    status: "in-progress",
    opened: "2026-06-04",
    summary:
      "A fee is quoted as a small annual percentage. It is applied to a compounding balance. I want to work out what that actually amounts to over forty years, and why the quoted number is misleading.",
  },
  {
    slug: "do-people-estimate-exponential-growth-badly",
    index: "R-04",
    question: "Do people my age systematically underestimate exponential growth?",
    field: "Behaviour",
    status: "open",
    opened: "2026-07-21",
    summary:
      "A small survey among classmates: ask them to guess the 30-year value before showing any arithmetic, and measure the size and direction of the error.",
  },
];

export function getEntry(slug: string) {
  return entries.find((e) => e.slug === slug);
}
